# Generated by Django 5.2.15 on 2026-09-07 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReminderLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('due_reminder', 'Due reminder'), ('overdue', 'Overdue')], max_length=32)),
                ('target_date', models.DateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='db.issue')),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_logs', to='db.notification')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reminder_logs', to='db.project')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reminder_logs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reminder_logs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Reminder Log',
                'verbose_name_plural': 'Issue Reminder Logs',
                'db_table': 'issue_reminder_logs',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('issue', 'receiver', 'kind', 'target_date'), name='issue_reminder_log_unique_issue_receiver_kind_date')],
            },
        ),
    ]
