# Generated by Django 5.2.15 on 2026-09-08 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_issuereminderlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueDependencySchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dependency_finish_date', models.DateField()),
                ('adjusted_start_date', models.DateField(blank=True, null=True)),
                ('adjusted_target_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('delayed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_delayed_issues', to='db.issue')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_schedule', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Dependency Schedule',
                'verbose_name_plural': 'Issue Dependency Schedules',
                'db_table': 'issue_dependency_schedules',
                'ordering': ('-created_at',),
            },
        ),
    ]
