# Generated by Django 5.2.15 on 2026-09-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_issuedependencyschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Module Code'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('module_code__isnull', False)), fields=('module_code', 'project'), name='module_unique_module_code_project_when_deleted_at_null'),
        ),
    ]
