# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

ERROR_CODES = {
    # issues
    "INVALID_ARCHIVE_STATE_GROUP": 4091,
    "INVALID_ISSUE_DATES": 4100,
    "INVALID_ISSUE_START_DATE": 4101,
    "INVALID_ISSUE_TARGET_DATE": 4102,
    "DUE_DATE_LOCKED": 4103,
    "DUE_DATE_CHANGE_REQUEST_EXISTS": 4104,
    "DUE_DATE_CHANGE_REQUEST_NOT_PENDING": 4105,
    "DUE_DATE_CHANGE_REQUEST_SAME_DATE": 4106,
    "DUE_DATE_NOT_LOCKED": 4107,
    # pages
    "PAGE_LOCKED": 4701,
    "PAGE_ARCHIVED": 4702,
}
